document:
  name: Guida utente di Web Analytics Italia
  description:
    La guida utente di Web Analytics Italia spiega le principali procedure di utilizzo della piattaforma.
  tags:
    - WAI
    - Web Analytics Italia
    - Statistiche
    - Guida utente
